### ISSUE TITLE
why go.sum listed in .gitignore file?

### ISSUE THREAD

**Issue by SaeedDev94** [XTLS/libXray#18]
As my understanding `go.sum` is like npm `package-lock.json` which guarantees the dependencies versions be exactly same as author machine  
Why it listed in `.gitignore` file?  
When i run `go mod download` to install dependencies go command updates libs so I have to commit the changes (`go.mod`) which I don't want to do it!  
I saw other go repos that contains this file  
Please include it if there is no specific reason for that, Thanks

**Comment by yiguous** [comment]
There is no need to do this.
If you use build.sh to compile libXray, it will delete the go.mod file and always use the latest Xray-core version.
You can find the codes here:

[prepare_go() {](https://github.com/XTLS/libXray/blob/fc890d234c8cfdc954aabdb3db450ad85afeaf06/build.sh#L3)

**Comment by SaeedDev94** [comment]
> There is no need to do this. If you use build.sh to compile libXray, it will delete the go.mod file and always use the latest Xray-core version. You can find the codes here:
> 
> [prepare_go() {](https://github.com/XTLS/libXray/blob/fc890d234c8cfdc954aabdb3db450ad85afeaf06/build.sh#L3)

@yiguous The `Xray-core` version isn't the problem at all, the problem is updating `go.mod` after running the build script, it should install the dependencies without updating any files IMO

**Comment by yiguous** [comment]
I know what you mean. If I remove go.sum from .ignore file, the updating of dependencies will depend on when I build the libXray. It is an annoying job. And I always use latest Xray-core version when developing libXray, so there is no difference between what I do and what you say. The dependencies will be updated frequently.

**Comment by SaeedDev94** [comment]
> I know what you mean. If I remove go.sum from .ignore file, the updating of dependencies will depend on when I build the libXray. It is an annoying job. And I always use latest Xray-core version when developing libXray, so there is no difference between what I do and what you say. The dependencies will be updated frequently.

@yiguous Let me give you an example  
I as a developer using `libXray` for my own app and I create a tag for my repo (ex v2.0.0)  
If someone wants to build my app from its source for v2.0.0 (`git checkout v2.0.0`) the output build wouldn't be same as I build it and upload it to my repo releases (build's md5sum definitely would be different)

**Comment by yiguous** [comment]
OK. I see it. I will remove go.sum from .ignore file and publish a new tag.
