### ISSUE TITLE
libxray占用异常

### ISSUE THREAD

**Issue by CraneSleep** [XTLS/libXray#27]
![Screenshot_2024-04-02-09-02-03-530_com omarea vtools](https://github.com/XTLS/libXray/assets/83820216/74662725-0505-4b00-b765-36dabec225d0)
miui14，偶然发现手机发烫变卡，看进程发现libxray.so把cpu吃满了，重启后恢复正常

**Comment by yiguous** [comment]
libXray 在 Android 上建议的接入方式为 “使用 gomobile 编译为 aar”。
当使用 cgo 编译为 so 时，需要开发者具备 cgo 使用基础，否则极易产生内存泄漏。
建议联系 App 作者。
