### ISSUE TITLE
在iOS项目中使用Libxray.xcframework的咨询

### ISSUE THREAD

**Issue by houmie** [XTLS/libXray#3]
你好，

感谢你的精彩项目。

我已经为iOS编译了这个项目，并添加到我的项目中。我是否需要在我的PacketTunnelProvider中使用这个框架？例如，我是否可以在startTunnel()等函数中直接运行LibxrayRunXray()？

请问有关于如何在iOS中使用这个框架的文档吗？

谢谢你，

**Comment by yiguous** [comment]
[Mango](https://github.com/arror/Mango) is a very good open-source project. If you know little about Network Extension or Xray-core, researching Mango is a better choice.
Currently, no document will be offered about this lib.

**Comment by houmie** [comment]
Hello @yiguous 

Thank you for your reply.  Yes, I have researched Mango in the last few days and now I understand how it works.

In Mango the environment variables are set, then the config file is stored into a file, then the Xray instance gets started and Tun2Socket establishes the connection. It makes sense to me.

In this lib here there is no environment variables. I think I have to start it directly:

`LibxrayRunXray(NSString* _Nullable datDir, NSString* _Nullable config, int64_t maxMemory);`

What is datDir?  cachesDirectory or assetDirectory or configDirectory ?
1) cachesDirectory = URL(fileURLWithPath: NSSearchPathForDirectoriesInDomains(.cachesDirectory, .userDomainMask, true).first!)

2) assetDirectory = TGConstant.createDirectory(at: TGConstant.homeDirectory.appendingPathComponent("assets", isDirectory: true)) 

3) configDirectory = TGConstant.createDirectory(at: TGConstant.homeDirectory.appendingPathComponent("configs", isDirectory: true))

And is config written in escaped JSON: 

> let configString = "{\"inbounds\":[{\"listen\":\"[::1]\",\"port\":8080,\"protocol\":\"socks\",\"settings... "

So that the finale looks like:

```
LibxrayRunXray(TGConstant.configDirectory.path, configString, 1024 * 1024 * 10)
```

Is this correct? 
Thank you so much

**Comment by yiguous** [comment]
Try to read the source code.

https://github.com/XTLS/libXray/blob/main/xray.go#L40
