### ISSUE TITLE
XcodeDefault.xctoolchain/usr/bin/bitcode_strip exited with 1

### ISSUE THREAD

**Issue by houmie** [XTLS/libXray#4]
After compiling this for apple:

`bash build.sh apple`

and adding `LibXray.xcframework` to my project, I can no longer build it.

I get this error:

> /Users/houmie/Projects/libXray/LibXray.xcframework/ios-arm64/LibXray.framework bitcode_strip /Users/houmie/Projects/libXray/LibXray.xcframework/ios-arm64/LibXray.framework/Versions/A/LibXray: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip exited with 1

The only way to circumvent it is to 
1) Add this in User Settings: `STRIP_BITCODE_FROM_COPIED_FILES=NO`
2) In Frameworks and Libraries change `Embed & Sign` to `Embed Without Signing`.

Is this intended like this?

**Comment by yiguous** [comment]
[bitcode is deprecated](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes#Deprecations).

Make sure using the latest Xcode version.

**Comment by houmie** [comment]
Hello @yiguous 

Yes, I know Bitcode is deprecated.  I don't want to use it. 

I have Xcode version 14.3.1 (14E300c)

What what can I do?  Thanks

**Comment by houmie** [comment]
@yiguous 

Well, it seems that your `build.sh` script has Bitcode enabled. You should remove it.

**Comment by yiguous** [comment]
I use all default configurations of gomobile, you can check them.

Maybe you can send your feedback to gomobile team.

**Comment by mishamoix** [comment]
@houmie Have you figured out how to solve it?
