### ISSUE TITLE
Exception: build failed

### ISSUE THREAD

**Issue by tensionc** [XTLS/libXray#40]
TensionMacBook-Pro:libXray tension$ python3 build/main.py apple gomobile
['build/main.py', 'apple', 'gomobile']
go: creating new go.mod: module github.com/xtls/libxray
go: to add module requirements and sums:
        go mod tidy
go: finding module for package github.com/xtls/xray-core/transport/internet
go: finding module for package github.com/xtls/xray-core/common/cmdarg
go: finding module for package github.com/xtls/xray-core/app/router
go: finding module for package github.com/xtls/xray-core/core
go: finding module for package github.com/xtls/xray-core/common/uuid
go: finding module for package google.golang.org/grpc/credentials/insecure
go: finding module for package github.com/xtls/xray-core/main/distro/all
go: finding module for package gopkg.in/yaml.v3
go: finding module for package google.golang.org/protobuf/encoding/protojson
go: finding module for package google.golang.org/grpc
go: finding module for package github.com/xtls/xray-core/app/stats/command
go: finding module for package google.golang.org/protobuf/proto
go: found github.com/xtls/xray-core/transport/internet in github.com/xtls/xray-core v1.8.24
go: found gopkg.in/yaml.v3 in gopkg.in/yaml.v3 v3.0.1
go: found github.com/xtls/xray-core/app/router in github.com/xtls/xray-core v1.8.24
go: found github.com/xtls/xray-core/app/stats/command in github.com/xtls/xray-core v1.8.24
go: found github.com/xtls/xray-core/common/cmdarg in github.com/xtls/xray-core v1.8.24
go: found github.com/xtls/xray-core/common/uuid in github.com/xtls/xray-core v1.8.24
go: found github.com/xtls/xray-core/core in github.com/xtls/xray-core v1.8.24
go: found github.com/xtls/xray-core/main/distro/all in github.com/xtls/xray-core v1.8.24
go: found google.golang.org/grpc in google.golang.org/grpc v1.67.0
go: found google.golang.org/grpc/credentials/insecure in google.golang.org/grpc v1.67.0
go: found google.golang.org/protobuf/encoding/protojson in google.golang.org/protobuf v1.34.2
go: found google.golang.org/protobuf/proto in google.golang.org/protobuf v1.34.2
zgo: upgraded golang.org/x/crypto v0.26.0 => v0.27.0
go: added golang.org/x/mobile v0.0.0-20240909163608-642950227fb3
go: upgraded golang.org/x/mod v0.18.0 => v0.21.0
go: upgraded golang.org/x/net v0.28.0 => v0.29.0
go: upgraded golang.org/x/sys v0.24.0 => v0.25.0
go: upgraded golang.org/x/text v0.17.0 => v0.18.0
go: upgraded golang.org/x/tools v0.22.0 => v0.25.0
gomobile: go mod tidy failed: exit status 1
go: found github.com/xtls/libxray in github.com/xtls/libxray v0.0.0-00010101000000-000000000000
go: gobind/gobind imports
        github.com/xtls/libxray imports
        github.com/xtls/libxray/xray imports
        github.com/xtls/xray-core/app/stats/command imports
        google.golang.org/grpc/status imports
        google.golang.org/genproto/googleapis/rpc/status: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/status in multiple modules:
        google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f (/Users/tension/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230110181048-76db0878b65f/googleapis/rpc/status)
        google.golang.org/genproto/googleapis/rpc v0.0.0-20240814211410-ddb44dafa142 (/Users/tension/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240814211410-ddb44dafa142/status)
go: gobind/gobind imports
        github.com/xtls/libxray imports
        github.com/xtls/libxray/xray imports
        github.com/xtls/xray-core/app/stats/command imports
        google.golang.org/grpc/codes tested by
        google.golang.org/grpc/codes.test imports
        google.golang.org/genproto/googleapis/rpc/code: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/code in multiple modules:
        google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f (/Users/tension/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230110181048-76db0878b65f/googleapis/rpc/code)
        google.golang.org/genproto/googleapis/rpc v0.0.0-20240814211410-ddb44dafa142 (/Users/tension/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240814211410-ddb44dafa142/code)
go: gobind/gobind imports
        github.com/xtls/libxray imports
        github.com/xtls/libxray/xray imports
        github.com/xtls/xray-core/app/stats/command imports
        google.golang.org/grpc/status tested by
        google.golang.org/grpc/status.test imports
        google.golang.org/genproto/googleapis/rpc/errdetails: ambiguous import: found package google.golang.org/genproto/googleapis/rpc/errdetails in multiple modules:
        google.golang.org/genproto v0.0.0-20230110181048-76db0878b65f (/Users/tension/go/pkg/mod/google.golang.org/genproto@v0.0.0-20230110181048-76db0878b65f/googleapis/rpc/errdetails)
        google.golang.org/genproto/googleapis/rpc v0.0.0-20240814211410-ddb44dafa142 (/Users/tension/go/pkg/mod/google.golang.org/genproto/googleapis/rpc@v0.0.0-20240814211410-ddb44dafa142/errdetails)

Traceback (most recent call last):
  File "/Users/tension/code/libXray/build/main.py", line 27, in <module>
    builder.build()
  File "/Users/tension/code/libXray/build/app/apple_gomobile.py", line 28, in build
    raise Exception("build failed")
Exception: build failed

**Comment by yiguous** [comment]
Fixed. Please try v3.1.0 or main branch.
Please note: QueryStats has changed.
