### ISSUE TITLE
关于LibXrayPing的问题

### ISSUE THREAD

**Issue by wanliyunyan** [XTLS/libXray#44]
1. 调用LibXrayRunXray后，再调用LibXrayPing，程序会崩溃
2. 调用LibXrayRunXray前，调用LibXrayPing能正常运行，再次调用LibXrayPing程序会崩溃

对于LibXrayPing使用有什么规范吗？

**Comment by yiguous** [comment]
[duplicate](https://github.com/XTLS/libXray/issues/43#issuecomment-2398563277)
