### ISSUE TITLE
Mac - Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by houmie** [XTLS/libXray#5]
Today I started implementing a demo on Mac with this lib.

I can't build it though.

```
/Users/houmie/Library/Developer/Xcode/DerivedData/xraydemo-akmagyiewjmaxhgqegcdimbvucrm/Build/Products/Debug/tunnel-mac.appex: code object is not signed at all
In subcomponent: /Users/houmie/Library/Developer/Xcode/DerivedData/xraydemo-akmagyiewjmaxhgqegcdimbvucrm/Build/Products/Debug/tunnel-mac.appex/Contents/Frameworks/Libxray.framework
Command CodeSign failed with a nonzero exit code
```

I have already set it to Embed Without Signing.

<img width="678" alt="Screenshot 2023-07-09 at 12 21 17" src="https://github.com/XTLS/libXray/assets/1832933/3d20b684-3a4a-4ca1-9ee6-698fcc393ee9">

But it doesn't work.

Any advice please?

**Comment by yiguous** [comment]
Use "Do Not Embed"

**Comment by houmie** [comment]
Thanks, that is an option to get it working on my machine locally.  But if I want to compile it and distribute it on AppStore, it will no longer work because your library is not a system library, correct? I don't think that's the right solution, unless I'm missing something.

**Comment by ZaneCode6574** [comment]
> Thanks, that is an option to get it working on my machine locally. But if I want to compile it and distribute it on AppStore, it will no longer work because your library is not a system library, correct? I don't think that's the right solution, unless I'm missing something.

Just copy the code you need to a single go file and compile it to a static library.

**Comment by yiguous** [comment]
> Thanks, that is an option to get it working on my machine locally. But if I want to compile it and distribute it on AppStore, it will no longer work because your library is not a system library, correct? I don't think that's the right solution, unless I'm missing something.

I always use "Do Not Embed" to integrate LibXray.xcframework. I never meet your problem.

**Comment by houmie** [comment]
> I always use "Do Not Embed" to integrate LibXray.xcframework. I never meet your problem.

Beware that when you are testing in Debug mode, Xcode always includes third party libraries in the bundle, no matter if you choose "Do Not Embed".  However in Release Mode, the app should crash, because the library is not included in the bundle.

Have you uploaded your project with this library as Release mode to AppStore and tested it via TestFlight on your Mac? 

Thanks

**Comment by yiguous** [comment]
> > I always use "Do Not Embed" to integrate LibXray.xcframework. I never meet your problem.
> 
> Beware that when you are testing in Debug mode, Xcode always includes third party libraries in the bundle, no matter if you choose "Do Not Embed". However in Release Mode, the app should crash, because the library is not included in the bundle.
> 
> Have you uploaded your project with this library as Release mode to AppStore and tested it via TestFlight on your Mac?
> 
> Thanks

Yes.

**Comment by houmie** [comment]
Ok, thank you. Maybe I made a mistake.  I'll try again.

**Comment by yiguous** [comment]
> Today I started implementing a demo on Mac with this lib.
> 
> I can't build it though.
> 
> ```
> /Users/houmie/Library/Developer/Xcode/DerivedData/xraydemo-akmagyiewjmaxhgqegcdimbvucrm/Build/Products/Debug/tunnel-mac.appex: code object is not signed at all
> In subcomponent: /Users/houmie/Library/Developer/Xcode/DerivedData/xraydemo-akmagyiewjmaxhgqegcdimbvucrm/Build/Products/Debug/tunnel-mac.appex/Contents/Frameworks/Libxray.framework
> Command CodeSign failed with a nonzero exit code
> ```
> 
> I have already set it to Embed Without Signing.
> 
> <img alt="Screenshot 2023-07-09 at 12 21 17" width="678" src="https://user-images.githubusercontent.com/1832933/252141977-3d20b684-3a4a-4ca1-9ee6-698fcc393ee9.png">
> But it doesn't work.
> 
> Any advice please?

I checked my configuration carefully. I found you missed **libresolv.tbd**. Try to add it. According to gomobile's issue, you need add it.

**Comment by houmie** [comment]
Yes, you're right. I added it now. 

<img width="540" alt="Screenshot 2023-07-10 at 08 06 15" src="https://github.com/XTLS/libXray/assets/1832933/a7612081-40ab-42a5-9b14-c9f6748836bd">
