### ISSUE TITLE
LibXrayQueryStats() for usage traffic

### ISSUE THREAD

**Issue by houmie** [XTLS/libXray#6]
Hello,

What is the best way to get the usage (traffic)?

```
import UIKit
import NetworkExtension
import LibXray

class ViewController: UIViewController {
    
    var tunnelProviderManager: NETunnelProviderManager?
    var isTimerUsageRunning = false
    var timerUsage = Timer()

    override func viewDidLoad() {
        super.viewDidLoad()
        if self.isTimerUsageRunning == false {
            self.isTimerUsageRunning = true
            self.timerUsage = Timer.scheduledTimer(withTimeInterval: 1, repeats: true, block: { [self] _ in
                LibXrayQueryStats("127.0.0.1:8080", TGConstant.homeDirectory.absoluteString + "\test.json")
            })
        }
}
```

I try to get the stats written to test.json every second. Is this the correct approach?

When I try to run this on my iPhone I get a crash. I believe the main app's target is not happy that I added LibXray.xcframework to it.  It seems it's only ok when I add that to the tunnel (network extension)'s target.

What am I missing, please?

```
Unable to install "xraydemo"
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTErrorCreationDateKey = "2023-07-10 23:18:51 +0000";
    IDERunOperationFailingWorker = IDEInstalliPhoneLauncher;
}
--
Could not inspect the application package.
Domain: com.apple.dt.MobileDeviceErrorDomain
Code: -402653103
User Info: {
    DVTRadarComponentKey = 282703;
    MobileDeviceErrorCode = "(0xE8000051)";
    "com.apple.dtdevicekit.stacktrace" = (
	0   DTDeviceKitBase                     0x000000010b588b1c DTDKCreateNSErrorFromAMDErrorCode + 300
	1   DTDeviceKitBase                     0x000000010b5bd000 __90-[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:]_block_invoke + 136
	2   DVTFoundation                       0x0000000101f23480 DVTInvokeWithStrongOwnership + 76
	3   DTDeviceKitBase                     0x000000010b5bcd7c -[DTDKMobileDeviceToken installApplicationBundleAtPath:withOptions:andError:withCallback:] + 1208
	4   IDEiOSSupportCore                   0x000000010b473c00 __118-[DVTiOSDevice(DVTiPhoneApplicationInstallation) processAppInstallSet:appUninstallSet:installOptions:completionBlock:]_block_invoke.147 + 2340
	5   DVTFoundation                       0x000000010202dde0 __DVT_CALLING_CLIENT_BLOCK__ + 16
	6   DVTFoundation                       0x000000010202e84c __DVTDispatchAsync_block_invoke + 152
	7   libdispatch.dylib                   0x00000001a9ce2874 _dispatch_call_block_and_release + 32
	8   libdispatch.dylib                   0x00000001a9ce4400 _dispatch_client_callout + 20
	9   libdispatch.dylib                   0x00000001a9ceba88 _dispatch_lane_serial_drain + 668
	10  libdispatch.dylib                   0x00000001a9cec5f8 _dispatch_lane_invoke + 384
	11  libdispatch.dylib                   0x00000001a9cf7244 _dispatch_workloop_worker_thread + 648
	12  libsystem_pthread.dylib             0x00000001a9e90074 _pthread_wqthread + 288
	13  libsystem_pthread.dylib             0x00000001a9e8ed94 start_wqthread + 8
);
}
--

Analytics Event: com.apple.dt.IDERunOperationWorkerFinished : {
    "device_model" = "iPhone15,3";
    "device_osBuild" = "16.5.1 (20F75)";
    "device_platform" = "com.apple.platform.iphoneos";
    "launchSession_schemeCommand" = Run;
    "launchSession_state" = 1;
    "launchSession_targetArch" = arm64;
    "operation_duration_ms" = 5668;
    "operation_errorCode" = "-402653103";
    "operation_errorDomain" = "com.apple.dt.MobileDeviceErrorDomain";
    "operation_errorWorker" = IDEInstalliPhoneLauncher;
    "operation_name" = IDEiPhoneRunOperationWorkerGroup;
    "param_consoleMode" = 0;
    "param_debugger_attachToExtensions" = 0;
    "param_debugger_attachToXPC" = 1;
    "param_debugger_type" = 5;
    "param_destination_isProxy" = 0;
    "param_destination_platform" = "com.apple.platform.iphoneos";
    "param_diag_MainThreadChecker_stopOnIssue" = 0;
    "param_diag_MallocStackLogging_enableDuringAttach" = 0;
    "param_diag_MallocStackLogging_enableForXPC" = 1;
    "param_diag_allowLocationSimulation" = 1;
    "param_diag_checker_tpc_enable" = 1;
    "param_diag_gpu_frameCapture_enable" = 0;
    "param_diag_gpu_shaderValidation_enable" = 0;
    "param_diag_gpu_validation_enable" = 0;
    "param_diag_memoryGraphOnResourceException" = 0;
    "param_diag_queueDebugging_enable" = 1;
    "param_diag_runtimeProfile_generate" = 0;
    "param_diag_sanitizer_asan_enable" = 0;
    "param_diag_sanitizer_tsan_enable" = 0;
    "param_diag_sanitizer_tsan_stopOnIssue" = 0;
    "param_diag_sanitizer_ubsan_stopOnIssue" = 0;
    "param_diag_showNonLocalizedStrings" = 0;
    "param_diag_viewDebugging_enabled" = 1;
    "param_diag_viewDebugging_insertDylibOnLaunch" = 1;
    "param_install_style" = 0;
    "param_launcher_UID" = 2;
    "param_launcher_allowDeviceSensorReplayData" = 0;
    "param_launcher_kind" = 0;
    "param_launcher_style" = 0;
    "param_launcher_substyle" = 0;
    "param_runnable_appExtensionHostRunMode" = 0;
    "param_runnable_productType" = "com.apple.product-type.application";
    "param_testing_launchedForTesting" = 0;
    "param_testing_suppressSimulatorApp" = 0;
    "param_testing_usingCLI" = 0;
    "sdk_canonicalName" = "iphoneos16.4";
    "sdk_osVersion" = "16.4";
    "sdk_variant" = iphoneos;
}
--


System Information

macOS Version 13.4.1 (Build 22F82)
Xcode 14.3.1 (21815) (Build 14E300c)
Timestamp: 2023-07-11T00:18:51+01:00
```

**Comment by yiguous** [comment]
You must know, this is not a iOS developer community. You should finish this by yourself. I will NOT reply every issue about iOS developing.

**Comment by houmie** [comment]
Apologies for the misunderstanding. I completely understand.

I have created a demo project just to learn the wrapper and everything else works great. I can start, stop and use configs.  You did a fantastic job with this project. Just sometimes the description of the methods isn't clear to me like the LibXrayQueryStats().

In particular the strategy/restriction behind it in Go isn't clear. Is it ok to call the method every minute to get the statistics? Or is the method allowed to be called from the main target? 

But no problem, I understand. Maybe it would make sense to enable the "Discussion" tap on your GitHub project, so that other users have the option to help each other. That would be great, because I know you're busy.

Thanks again for this great project.

**Comment by houmie** [comment]
Hello friend @yiguous 

I think the issue is in Go.

Checkout this [line](https://github.com/XTLS/libXray/blob/949a83d683e418b7b107b5079d8f738a5f998362/api.go#L51C3-L51C3)

I have added a more descriptive error message in your Go library and compiled it afterwards again:
```
if err != nil {
    fmt.Println("Directory Error: " + err.Error())
    return err.Error()
}
```

Then in Xcode when I execute the library:
`LibXrayQueryStats("127.0.0.1:10085", statFilePath)`

I get this error message:
> Directory Error: context deadline exceeded

This means it can't connect to 127.0.0.1:10085 within three seconds and it times out.

My config looks like this below. I know it's a bit hard to read. But you can see dokodemo-door is set to 127.0.01:10085.
Everything else is also in place.

`let dataString = "{\"api\": {\"services\": [\"HandlerService\",\"LoggerService\",\"StatsService\"],\"tag\": \"api\"},\"stats\": {},\"policy\": {\"levels\": {\"0\": {\"statsUserUplink\": true,\"statsUserDownlink\": true,\"handshake\":3,\"connIdle\":180}},\"system\": {\"statsInboundUplink\": true,\"statsInboundDownlink\": true,\"statsOutboundUplink\": true,\"statsOutboundDownlink\": true}},\"inbounds\":[{\"listen\": \"127.0.0.1\",\"port\": 10085,\"protocol\": \"dokodemo-door\",\"settings\": {\"address\": \"127.0.0.1\"},\"tag\": \"api\",\"sniffing\": null},{\"listen\":\"[::1]\",\"port\":8080,\"protocol\":\"socks\",\"settings\":{\"auth\":\"noauth\",\"udp\":true},\"sniffing\":{\"destOverride\":[\"http\",\"tls\"],\"enabled\":true,\"excludedDomains\":[],\"metadataOnly\":false,\"routeOnly\":false},\"tag\":\"socks-in\"}],\"outbounds\":[{\"protocol\":\"vless\",\"settings\":{\"vnext\":[{\"address\":\"xxx.xxx.xxx.xx\",\"port\":443,\"users\":[{\"encryption\":\"none\",\"flow\":\"xtls-rprx-vision\",\"id\":\"8652b34d-a236-4eca-8a08-b30ea4e63cba\"}]}]},\"streamSettings\":{\"network\":\"tcp\",\"realitySettings\":{\"fingerprint\":\"chrome\",\"publicKey\":\"eGZ4cJLCFo8gqCkFGuwxCRVx8FE3R2vh__uqCFZg6RM\",\"serverName\":\"www.google-analytics.com\",\"shortId\":\"1ad99ba959dec1a9\",\"show\":false,\"spiderX\":\"\"},\"security\":\"reality\",\"tcpSettings\":{\"header\":{\"type\":\"none\"}}},\"tag\":\"proxy\"},{\"protocol\":\"freedom\",\"tag\":\"direct\"},{\"protocol\":\"blackhole\",\"tag\":\"block\"}],\"routing\":{\"balancers\":[],\"domainMatcher\":\"hybrid\",\"domainStrategy\":\"IPIfNonMatch\",\"rules\":[{\"type\": \"field\",\"inboundTag\": [\"api\"],\"outboundTag\": \"api\"},{\"__enabled__\":true,\"__id__\":\"E88ACF9A-E85D-4C03-B2BF-43D0513613F3\",\"__name__\":\"Rule_E88ACF9A-E85D-4C03-B2BF-43D0513613F3\",\"domainMatcher\":\"hybrid\",\"network\":\"udp,tcp,\",\"outboundTag\":\"block\",\"protocol\":[\"bittorrent\"],\"type\":\"field\"}]}}"`

Unless I'm overlooking something. Have you tested this function and it works for you?

**Comment by yiguous** [comment]
This function works well. But I don't use it for production.

**Comment by houmie** [comment]
Ah that's great. May I ask which port did you use that worked for you? `127.0.0.1:??`

For me, no matter what port I use the Go function prints `context deadline exceeded`.
Thank you.

**Comment by yiguous** [comment]
> Ah that's great. May I ask which port did you use that worked for you? `127.0.0.1:??`
> 
> For me, no matter what port I use the Go function prints `context deadline exceeded`. Thank you.

Yes. I used 127.0.0.1 . But I think it has no relationship with ip which you listen.

I have decided to remove this api. Whatever, it is useless for production.

**Comment by houmie** [comment]
Ah I understand. Thank you for letting me know.

I suppose it would be useful if the user could see how much traffic has been used so far. It's nice to see that on the client. But I haven't seen any Xray client to do that. So maybe it's not possible.

It works on the server though. 
`xray api statsquery --server=127.0.0.1:10085 -pattern your@email.com`

It returns the download and upload for a particular user with the given email address:
```
{
    "stat":  [
        {
            "name":  "user>>>general@vless-tcp-xtls>>>traffic>>>downlink",
            "value":  "13013635"
        },
        {
            "name":  "user>>>general@vless-tcp-xtls>>>traffic>>>uplink",
            "value":  "1553233"
        }
    ]
}
```

It would be so cool if this information could also be gathered on Client side. But sadly I haven't found a way.

Have a good day,

**Comment by yiguous** [comment]
You can try V2Box, it has this feature.
